### ISSUE TITLE
Integración continua añadida

### ISSUE THREAD

**Issue by Tappedz** [noemigportillo/laravel-docker-CryptoAPI-src#21]

**Comment by noemigportillo** [comment]
Se ha visto que hay un error en la CI y se necesita cambiar `run: ./vendor/bin/grumphp` por `run: ./vendor/bin/grumphp run`

**Comment by Tappedz** [comment]
Al arreglar la integración continua, se comprueba que grumphp se ejecuta pero hay problemas con los archivos propios del proyecto y no relacionados con nuestra implementación. Para intentar solucionarlo se va a permitir a grumphp que solucione los errores presentes en esos archivos.
